url: https://brilab.github.io

title: BIRL仿生与智能机器人实验室

keywords: BIRL仿生与智能机器人实验室

description: BIRL仿生与智能机器人实验室

address: 广东省广州市大学城广东工业大学工学二号馆206（仿生与智能机器人实验室）

contacts: 管贻生教授

email: ysguan@gdut.edu.cn

exclude:
  - README.md
